export type ReportsLevel = 'BASIC' | 'ADVANCED' | 'FULL';

export const PLANS = {
  FREE: {
    code: 'FREE',
    name: 'Бесплатный',
    nameEn: 'Free',
    price: 0,
    priceMonthly: 0,
    currency: 'UZS',
    limits: {
      maxStores: 1,
      maxProducts: 30,
      maxOrdersPerMonth: 100,
      maxDeliveryZones: 2,
      loyaltyEnabled: false,
      procurementEnabled: false,
      analyticsLevel: 'basic' as const,
      customBotMessages: false,
      brandingWatermark: true,
      reportsLevel: 'BASIC' as ReportsLevel,
      reportsHistoryDays: 14,
      maxReportsPerMonth: 30,
      allowReportExport: false,
      maxScheduledReports: 0,
      maxExportsPerMonth: 0,
    },
    features: [
      '1 магазин',
      '30 товаров',
      '50 заказов/мес',
      '2 зоны доставки',
      'Базовая аналитика',
      'Базовые отчеты (14 дней)',
    ],
  },
  PRO: {
    code: 'PRO',
    name: 'Про',
    nameEn: 'Pro',
    price: 99_000,
    priceMonthly: 99_000,
    currency: 'UZS',
    limits: {
      maxStores: 3,
      maxProducts: 500,
      maxOrdersPerMonth: 1000,
      maxDeliveryZones: 10,
      loyaltyEnabled: true,
      procurementEnabled: true,
      analyticsLevel: 'full' as const,
      customBotMessages: true,
      brandingWatermark: false,
      reportsLevel: 'ADVANCED' as ReportsLevel,
      reportsHistoryDays: 90,
      maxReportsPerMonth: 300,
      allowReportExport: true,
      maxScheduledReports: 3,
      maxExportsPerMonth: 50,
    },
    features: [
      '3 магазина',
      '500 товаров',
      '1 000 заказов/мес',
      '10 зон доставки',
      'Программа лояльности',
      'Закупки',
      'Полная аналитика',
      'Расширенные отчеты + экспорт',
      'Без водяного знака',
    ],
  },
  BUSINESS: {
    code: 'BUSINESS',
    name: 'Бизнес',
    nameEn: 'Business',
    price: 199_000,
    priceMonthly: 199_000,
    currency: 'UZS',
    limits: {
      maxStores: 10,
      maxProducts: -1,
      maxOrdersPerMonth: -1,
      maxDeliveryZones: -1,
      loyaltyEnabled: true,
      procurementEnabled: true,
      analyticsLevel: 'full_export' as const,
      customBotMessages: true,
      brandingWatermark: false,
      reportsLevel: 'FULL' as ReportsLevel,
      reportsHistoryDays: 365,
      maxReportsPerMonth: -1,
      allowReportExport: true,
      maxScheduledReports: -1,
      maxExportsPerMonth: -1,
    },
    features: [
      '10 магазинов',
      'Безлимит товаров',
      'Безлимит заказов',
      'Безлимит зон',
      'Программа лояльности',
      'Закупки + экспорт',
      'Все отчеты + авто-отчеты',
      'Расширенная аналитика',
      'Приоритетная поддержка',
    ],
  },
} as const;

export type PlanCode = keyof typeof PLANS;
export type PlanLimits = (typeof PLANS)[PlanCode]['limits'];
