export const SHOP_READ_ERROR_STATUS: Record<string, number> = {
  PRODUCT_NOT_FOUND: 404,
  ORDER_NOT_FOUND: 404,
};

export const ORDER_ACTION_ERROR_STATUS: Record<string, number> = {
  ORDER_NOT_FOUND: 404,
  ORDER_CANNOT_CANCEL: 409,
  ORDER_CANNOT_REVIEW: 409,
  REVIEW_ALREADY_SUBMITTED: 409,
};

export const CART_ERROR_STATUS: Record<string, number> = {
  INVALID_INPUT: 400,
  INVALID_QTY: 400,
  PRODUCT_NOT_FOUND: 404,
  VARIANT_NOT_FOUND: 404,
  NOT_ENOUGH_STOCK: 400,
  ITEM_NOT_FOUND: 404,
};
